# Generated by Django 5.0.7 on 2024-07-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
